-- AERION command-control storage.
-- This file is intentionally not executed automatically.
--
-- The bot uses the existing SUPABASE_KEY through its server-side REST
-- helpers. Keep that key server-side/service-role; do not expose it to a
-- browser or Discord client. RLS is enabled with no public policies so the
-- tables are not writable through anon/authenticated client access.

create table if not exists public.aerion_command_controls (
    guild_id bigint not null,
    command_name text not null,
    enabled boolean not null default true,
    updated_by text,
    updated_at timestamptz not null default timezone('utc', now()),
    primary key (guild_id, command_name)
);

create table if not exists public.aerion_command_panels (
    guild_id bigint primary key,
    channel_id bigint not null,
    message_id bigint not null,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.aerion_command_audit (
    id bigint generated by default as identity primary key,
    guild_id bigint not null,
    command_name text not null,
    action text not null check (action in ('enabled', 'disabled')),
    actor_id text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists aerion_command_audit_guild_created_idx
    on public.aerion_command_audit (guild_id, created_at desc);

alter table public.aerion_command_controls enable row level security;
alter table public.aerion_command_panels enable row level security;
alter table public.aerion_command_audit enable row level security;