-- Separate storage for non-member/community share tracking.
-- The bot uses the server-side Supabase key, so these tables can remain
-- private behind Supabase RLS while the bot performs the REST writes.

create table if not exists public.community_share_profiles (
    id bigint generated by default as identity primary key,
    discord_id text not null unique,
    discord_name text not null,
    airline_name text not null,
    alliance text not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.community_share_entries (
    id bigint generated by default as identity primary key,
    profile_id bigint not null references public.community_share_profiles(id) on delete cascade,
    discord_id text not null,
    entry_date date not null,
    share_value numeric(20, 2) not null check (share_value > 0),
    created_at timestamptz not null default now(),
    constraint community_share_entries_one_per_day
        unique (profile_id, entry_date)
);

create index if not exists community_share_entries_profile_date_idx
    on public.community_share_entries (profile_id, entry_date desc);

create index if not exists community_share_entries_alliance_lookup_idx
    on public.community_share_profiles (alliance);

alter table public.community_share_profiles enable row level security;
alter table public.community_share_entries enable row level security;
